require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'
install! 'cocoapods', :deterministic_uuids => false
use_frameworks! :linkage => :static

target 'LiftPitch' do
  config = use_native_modules!
  flags = get_default_flags()
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.enabled,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )



  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod 'GoogleUtilities', :modular_headers => true;


  $RNFirebaseAsStaticFramework = true

  target 'LiftPitchTests' do
    inherit! :complete
    # Pods for testing
  end

  
end
