export const Routes = {
  Auth: {
    login: 'login',
    signUp: 'signUp',
    forgetPassword: 'forgetPassword',
    otp: 'otp',
    newPassword: 'newPassword',
    newPasswordSuccessScreen: 'newPasswordSuccessScreen',
  },
  GetStarting: {
    onBoarding: 'onBoarding',
  },
  Home: {
    homeScreen: 'home',
    bindBraceletScreen: 'bindBraceletScreen',
  },
  Profile: {
    profileUpdateScreen: 'profileUpdateScreen',
    profilePreviewScreen: 'profilePreviewScreen',
  },
  Container: {
    main: 'container',
  },
  DrawerStack: {
    main: 'drawerStack',
  },
  Contact: {
    contactScreen: 'contactScreen',
  },
  Function: {
    functionScreen: 'contactScreen',
    cardsListingScreen: 'cardsListingScreen',
    chooseCardScreen: 'chooseCardScreen',
    cardNameScreen: 'cardNameScreen',
    cardBackgroundScreen: 'cardBackgroundScreen',
    cardThemeColorScreen: 'cardThemeColorScreen',
    cardProfileUploadScreen: 'cardProfileUploadScreen',
    cardContactNumberScreen: 'cardContactNumberScreen',
    cardSocialMediaScreen: 'cardSocialMediaScreen',
    cardPersonalBioScreen: 'cardPersonalBioScreen',
    cardPreviewScreen: 'cardPreviewScreen',
    cardCompanyDetailsScreen: 'cardCompanyDetailsScreen',
    cardCompanyLogoScreen: 'cardCompanyLogoScreen',
    emergencyHomeScreen: 'emergencyHomeScreen',
    createEmergencyContactScreen: 'createEmergencyContactScreen',
    newEmergContactScreen: 'newEmergContactScreen',
    customUrlsHomeScreen: 'customUrlsHomeScreen',
    addCustomUrlScreen: 'addCustomUrlScreen',
    newCustomUrlScreen: 'newCustomUrlScreen',
    createPaymentScreen: 'createPaymentScreen',
    paymentHomeScreen: 'paymentHomeScreen',
    newPaymentScreen: 'newPaymentScreen',
    createUploadFilesScreen: 'createUploadFilesScreen',
    uploadFilesHomeScreen: 'uploadFilesHomeScreen',
    newUploadFilesScreen: 'newUploadFilesScreen',
    editCardScreen: 'editCardScreen',
  },
  Shop: {
    shopScreen: 'shopScreen',
  },
  Scan: {
    scanScreen: 'scanScreen',
  },
  DynamicStack: {
    dynamicScreen: 'dynamicScreen',
    dynamicDetail: 'dynamicDetail',
    addNewLink: 'addNewLink',
  },
  Settings: {
    settingsHomeScreen: 'settingsHomeScreen',
    helpFaqScreen: 'helpFaqScreen',
    changePassword: 'changePassword',
    settingsForgetPassScreen: 'settingsForgetPassScreen',
    settingsOtpScreen: 'settingsOtpScreen',
    settingsNewPassScreen: 'settingsNewPassScreen',
    settingsPassSuccessScreen: 'settingsPassSuccessScreen',
    upgradeAccount: 'upgradeAccount',
    addNewPassword: 'addNewPassword',
    aboutUs: 'aboutUs',
    contactUs: 'contactUs',
    tutorials: 'tutorials',
    termAndCondition: 'termAndCondition',
    privacyPolicy: 'privacyPolicy',
    faqScreen: 'faqScreen',
    aboutatSetting: 'aboutatSetting',
    notificationsListingScreen: 'notificationsListingScreen',
    exchangePolicyScreen: 'exchangePolicyScreen',
    IntellectualPropertyScreen: 'intellectualPropertyScreen',
    enterpriseContactForm: 'EnterpriseContactForm',
  },
  Teams: {
    teamNodes: 'teamNodes',
  },
};
